/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThreeCanvas: typeof import('./components/three-canvas/index.vue')['default']
    Ui: typeof import('./components/Ui.vue')['default']
    UiInputActionButtons: typeof import('./components/ui/input/ActionButtons.vue')['default']
    UiInputVirtualStick: typeof import('./components/ui/input/VirtualStick.vue')['default']
  }
}
